import Foundation

enum ScenePage: String, CaseIterable {
    case assistantDialogue = "AI聊天"
    case agreement = "EULA"
    case uploadEmpty = "上传作品-未上传主题"
    case uploadFilled = "上传作品-输入主题"
    case personalDetail = "个人信息"
    case reportPanel = "举报"
    case publicPersona = "他人主页"
    case creditShortage = "余额不足"
    case galleryDetail = "作品"
    case galleryPreview = "作品预览"
    case accessGate = "去登陆"
    case feelingEditor = "发布今日感受"
    case discover = "发现"
    case resetAccess = "忘记密码"
    case persona = "我的"
    case restrictPanel = "拉黑"
    case restrictConfirm = "拉黑弹窗"
    case spendConfirm = "支付"
    case weeklyFeeling = "本周心情"
    case signUp = "注册"
    case dialogueList = "消息"
    case entry = "登录注册页"
    case signIn = "登录页"
    case profileEditor = "编辑资料"
    case voiceDialogue = "聊天-语音"
    case directDialogue = "聊天"
    case settings = "设置"
    case repliesPanel = "评论区"
    case exitConfirm = "退出登录弹窗"
    case signOutConfirm = "退出登录确认"
    case wallet = "钱包"
    case home = "首页"
    case restrictedList = "黑名单"
}
